### ISSUE TITLE
[Usage]: nccl and cupy problem "no cupy" and "NCCL_ERROR_UNHANDLED_CUDA_ERROR" when use TP in wsl

### ISSUE THREAD

**Issue by yamosin** [PygmalionAI/aphrodite-engine#336]
### Your current environment

```(aph) omni@DESKTOP-CKDOHD3:~$ python env.py
Collecting environment information...
/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 2: out of memory (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 2.2.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A
OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35
Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 546.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      46 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             24
On-line CPU(s) list:                0-23
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
CPU family:                         6
Model:                              63
Thread(s) per core:                 2
Core(s) per socket:                 12
Socket(s):                          1
Stepping:                           2
BogoMIPS:                           4788.91
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi ept vpid ept_ad fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt flush_l1d arch_capabilities
Virtualization:                     VT-x
Hypervisor vendor:                  Microsoft
Virtualization type:                full
L1d cache:                          384 KiB (12 instances)
L1i cache:                          384 KiB (12 instances)
L2 cache:                           3 MiB (12 instances)
L3 cache:                           30 MiB (1 instance)
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        KVM: Mitigation: VMX disabled
Vulnerability L1tf:                 Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:                  Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:             Mitigation; PTI
Vulnerability Mmio stale data:      Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.2.0
[pip3] triton==2.2.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.2.0                    pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypiROCM Version: Could not collect
Aphrodite Version: 0.5.1
Aphrodite Build Flags:
CUDA Archs: Not Set; ROCm: Disabled
```

### How would you like to use Aphrodite?

I want to run this [TinyLlama](https://huggingface.co/TinyLlama/TinyLlama-1.1B-intermediate-step-955k-token-2T) with TP 2 or 4,but can only work on 1 gpu, setting tp will give me this error
if i use tp 2 or 4 it report cupy is not install, but pip list show it installed
this issue show up after I reset and reinstall fresh new wsl+aphrodite
before this issue, I can run with tp 2 but show a nccl error with tp 4 ```cupy_backends.cuda.libs.nccl.NcclError: NCCL_ERROR_UNHANDLED_CUDA_ERROR: unhandled cuda error (run with NCCL_DEBUG=INFO for details)```

**Comment by AlpinDale** [comment]
Try `--disable-custom-all-reduce`.

**Comment by yamosin** [comment]
> Try `--disable-custom-all-reduce`.

got same 
```
(aph) omni@DESKTOP-CKDOHD3:~$ python -m aphrodite.endpoints.openai.api_server --model TinyLLama/ -tp 2 --disable-custom-all-reduce
2024-03-16 18:05:04,993 INFO worker.py:1724 -- Started a local Ray instance.
INFO:     Initializing the Aphrodite Engine (v0.5.1) with the following config:
INFO:     Model = 'TinyLLama/'
INFO:     DataType = torch.bfloat16
INFO:     Model Load Format = auto
INFO:     Number of GPUs = 2
INFO:     Disable Custom All-Reduce = True
INFO:     Quantization Format = None
INFO:     Context Length = 2048
INFO:     Enforce Eager Mode = False
INFO:     KV Cache Data Type = auto
INFO:     KV Cache Params Path = None
INFO:     Device = cuda
Traceback (most recent call last):
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/cupy/__init__.py", line 17, in <module>
    from cupy import _core  # NOQA
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
ImportError: libnvrtc.so.12: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/modeling/megatron/cupy_utils.py", line 14, in <module>
    import cupy
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/cupy/__init__.py", line 19, in <module>
    raise ImportError(f'''
ImportError:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libnvrtc.so.12: cannot open shared object file: No such file or directory
================================================================


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/endpoints/openai/api_server.py", line 563, in <module>
    engine = AsyncAphrodite.from_engine_args(engine_args)
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/engine/async_aphrodite.py", line 676, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/engine/async_aphrodite.py", line 341, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/engine/async_aphrodite.py", line 410, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/engine/aphrodite_engine.py", line 113, in __init__
    self._init_workers_ray(placement_group)
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/engine/aphrodite_engine.py", line 282, in _init_workers_ray
    self._run_workers("init_model", cupy_port=get_open_port())
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/engine/aphrodite_engine.py", line 1028, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/task_handler/worker.py", line 104, in init_model
    init_distributed_environment(self.parallel_config, self.rank,
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/task_handler/worker.py", line 287, in init_distributed_environment
    cupy_utils.init_process_group(
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/modeling/megatron/cupy_utils.py", line 76, in init_process_group
    raise ImportError(
ImportError: NCCLBackend is not available. Please install cupy.```

**Comment by AlpinDale** [comment]
Shouldn't you have cupy installed? Do `pip install cupy-cuda12x` (or cupy-cuda11x) and try again.

**Comment by yamosin** [comment]
```(aph) omni@DESKTOP-CKDOHD3:~$ pip list
Package                   Version
------------------------- -----------
aiohttp                   3.9.3
aiosignal                 1.3.1
annotated-types           0.6.0
anyio                     4.3.0
aphrodite-engine          0.5.1
async-timeout             4.0.3
attrs                     23.2.0
bitsandbytes              0.43.0
certifi                   2024.2.2
charset-normalizer        3.3.2
click                     8.1.7
cloudpickle               3.0.0
colorlog                  6.8.2
**cupy-cuda12x              12.3.0
diskcache                 5.6.3
distro                    1.9.0
einops                    0.7.0
exceptiongroup            1.2.0
fastapi                   0.110.0
fastrlock                 0.8.2
filelock                  3.13.1
frozenlist                1.4.1
fschat                    0.2.36
fsspec                    2024.3.0
h11                       0.14.0
httpcore                  1.0.4
httpx                     0.27.0
huggingface-hub           0.21.4
idna                      3.6
interegular               0.3.3
Jinja2                    3.1.3
joblib                    1.3.2
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
lark                      1.1.8
llvmlite                  0.42.0
loguru                    0.7.2
markdown-it-py            3.0.0
markdown2                 2.4.13
MarkupSafe                2.1.5
mdurl                     0.1.2
mpmath                    1.3.0
msgpack                   1.0.8
multidict                 6.0.5
nest-asyncio              1.6.0
networkx                  3.2.1
nh3                       0.2.15
ninja                     1.11.1.1
numba                     0.59.0
numpy                     1.26.4
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.19.3
nvidia-nvjitlink-cu12     12.4.99
nvidia-nvtx-cu12          12.1.105
openai                    1.14.1
outlines                  0.0.36
packaging                 24.0
pip                       23.3.1
prometheus_client         0.20.0
prompt-toolkit            3.0.43
protobuf                  5.26.0
psutil                    5.9.8
pydantic                  2.6.4
pydantic_core             2.16.3
Pygments                  2.17.2
pynvml                    11.5.0
PyYAML                    6.0.1
ray                       2.9.3
referencing               0.34.0
regex                     2023.12.25
requests                  2.31.0
rich                      13.7.1
rpds-py                   0.18.0
safetensors               0.4.2
scipy                     1.12.0
sentencepiece             0.2.0
setuptools                68.2.2
shortuuid                 1.0.13
six                       1.16.0
sniffio                   1.3.1
starlette                 0.36.3
svgwrite                  1.4.3
sympy                     1.12
tiktoken                  0.6.0
tokenizers                0.15.2
torch                     2.2.0
tqdm                      4.66.2
transformers              4.38.2
triton                    2.2.0
typing_extensions         4.10.0
urllib3                   2.2.1
uvicorn                   0.28.0
wavedrom                  2.0.3.post3
wcwidth                   0.2.13
wheel                     0.41.2
xformers                  0.0.24
yarl                      1.9.4```

**Comment by yamosin** [comment]
This is totally confusing me, I was using aphrodite version 0.5.0 yesterday (installed a few days ago) and was able to use tp 2, but tp 4 error
So I tried resetting WSL and freshly installing 0.5.1 without changing Windows drivers or environment parameters and now it has this problem,
I tried installing 0.5.0 again and it still has this problem and doesn't work on TP 2 ...

**Comment by AlpinDale** [comment]
Does this only happen with tinyllama?

**Comment by yamosin** [comment]
on every model, I just use tinyllama for test

**Comment by yamosin** [comment]
this is yesterday record, it can run on tp 2, but now it can only work with 1 gpu
```omnisaa@DESKTOP-CKDOHD3:~$ python3 -m aphrodite.endpoints.openai.api_server --model /home/omnisaa/TinyLLama/ -tp 2
2024-03-16 19:51:30,881 INFO worker.py:1724 -- Started a local Ray instance.
INFO:     Initializing the Aphrodite Engine (v0.5.0) with the following config:
INFO:     Model = '/home/omnisaa/TinyLLama/'
INFO:     DataType = torch.bfloat16
INFO:     Model Load Format = auto
INFO:     Number of GPUs = 2
INFO:     Disable Custom All-Reduce = False
INFO:     Quantization Format = None
INFO:     Context Length = 2048
INFO:     Enforce Eager Mode = False
INFO:     KV Cache Data Type = auto
INFO:     KV Cache Params Path = None
INFO:     Device = cuda
WARNING:  Custom allreduce is disabled because your platform lacks GPU P2P capability. To slience this warning, specify disable_custom_all_reduce=True
explicitly.
(RayWorkerAphrodite pid=62942) WARNING:  Custom allreduce is disabled because your platform lacks GPU P2P capability. To slience this warning, specify disable_custom_all_reduce=True
(RayWorkerAphrodite pid=62942) explicitly.
INFO:     Model loaded. Memory usage: 1.02 GiB
(RayWorkerAphrodite pid=62942) INFO:     Model loaded. Memory usage: 1.02 GiB
INFO:     # GPU blocks: 119225, # CPU blocks: 23831
INFO:     Minimum concurrency: 931.45x
INFO:     Maximum sequence length allowed in the cache: 1907600
```

and this is tp 4 error
```
INFO:     Initializing the Aphrodite Engine (v0.5.0) with the following config:
INFO:     Model = '/home/omnisaa/TinyLLama/'
INFO:     DataType = torch.bfloat16
INFO:     Model Load Format = auto
INFO:     Number of GPUs = 4
INFO:     Disable Custom All-Reduce = False
INFO:     Quantization Format = None
INFO:     Context Length = 2048
INFO:     Enforce Eager Mode = False
INFO:     KV Cache Data Type = auto
INFO:     KV Cache Params Path = None
INFO:     Device = cuda
WARNING:  Possibly too large swap space. 16.00 GiB out of the 31.30 GiB total CPU memory is allocated for the swap
space.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/omnisaa/.local/lib/python3.10/site-packages/aphrodite/endpoints/openai/api_server.py", line 561, in <module>
    engine = AsyncAphrodite.from_engine_args(engine_args)
  File "/home/omnisaa/.local/lib/python3.10/site-packages/aphrodite/engine/async_aphrodite.py", line 676, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/home/omnisaa/.local/lib/python3.10/site-packages/aphrodite/engine/async_aphrodite.py", line 341, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/omnisaa/.local/lib/python3.10/site-packages/aphrodite/engine/async_aphrodite.py", line 410, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/omnisaa/.local/lib/python3.10/site-packages/aphrodite/engine/aphrodite_engine.py", line 111, in __init__
    self._init_workers_ray(placement_group)
  File "/home/omnisaa/.local/lib/python3.10/site-packages/aphrodite/engine/aphrodite_engine.py", line 280, in _init_workers_ray
    self._run_workers("init_model", cupy_port=get_open_port())
  File "/home/omnisaa/.local/lib/python3.10/site-packages/aphrodite/engine/aphrodite_engine.py", line 1025, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/home/omnisaa/.local/lib/python3.10/site-packages/aphrodite/task_handler/worker.py", line 103, in init_model
    init_distributed_environment(self.parallel_config, self.rank,
  File "/home/omnisaa/.local/lib/python3.10/site-packages/aphrodite/task_handler/worker.py", line 286, in init_distributed_environment
    cupy_utils.init_process_group(
  File "/home/omnisaa/.local/lib/python3.10/site-packages/aphrodite/modeling/megatron/cupy_utils.py", line 87, in init_process_group
    _NCCL_BACKEND = NCCLBackendWithBFloat16(world_size, rank, host, port)
  File "/home/omnisaa/.local/lib/python3.10/site-packages/cupyx/distributed/_nccl_comm.py", line 70, in __init__
    self._init_with_tcp_store(n_devices, rank, host, port)
  File "/home/omnisaa/.local/lib/python3.10/site-packages/cupyx/distributed/_nccl_comm.py", line 100, in _init_with_tcp_store
    self._comm = nccl.NcclCommunicator(n_devices, nccl_id, rank)
  File "cupy_backends/cuda/libs/nccl.pyx", line 283, in cupy_backends.cuda.libs.nccl.NcclCommunicator.__init__
  File "cupy_backends/cuda/libs/nccl.pyx", line 129, in cupy_backends.cuda.libs.nccl.check_status
cupy_backends.cuda.libs.nccl.NcclError: NCCL_ERROR_UNHANDLED_CUDA_ERROR: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
```

**Comment by yamosin** [comment]
oh great, i think i fix the cupy issue
I use `find -name libnvrtc.so.12` to find the folder, then use `export LB_LIBRARY_PATH=./miniconda3/envs/aph/lib/python3.10/site-packages/nvidia/cuda_nvrtc/lib/:$LD_LIBRARY_PATH`, now it can found libnvrtc.so.12 correct (but I never do this before so I have no idea why it work yesterday)

```(aph) omni@DESKTOP-CKDOHD3:~$ python -m aphrodite.endpoints.openai.api_server --model TinyLLama/ -tp 2 --disable-custom-
all-reduce
2024-03-16 18:34:03,593 INFO worker.py:1724 -- Started a local Ray instance.
INFO:     Initializing the Aphrodite Engine (v0.5.1) with the following config:
INFO:     Model = 'TinyLLama/'
INFO:     DataType = torch.bfloat16
INFO:     Model Load Format = auto
INFO:     Number of GPUs = 2
INFO:     Disable Custom All-Reduce = True
INFO:     Quantization Format = None
INFO:     Context Length = 2048
INFO:     Enforce Eager Mode = False
INFO:     KV Cache Data Type = auto
INFO:     KV Cache Params Path = None
INFO:     Device = cuda
INFO:     Model weights loaded. Memory usage: 1.02 GiB x 2 = 2.05 GiB
(RayWorkerAphrodite pid=17727) INFO:     Model weights loaded. Memory usage: 1.02 GiB x 2 = 2.05 GiB
INFO:     # GPU blocks: 119225, # CPU blocks: 23831
INFO:     Minimum concurrency: 931.45x
INFO:     Maximum sequence length allowed in the cache: 1907600
WARNING:  Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
INFO:     Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To
run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
WARNING:  CUDA graphs can take additional 1~3 GiB of memory per GPU. If you are running out of memory, consider
decreasing `gpu_memory_utilization` or enforcing eager mode.
(RayWorkerAphrodite pid=17727) WARNING:  Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
(RayWorkerAphrodite pid=17727) INFO:     Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To
(RayWorkerAphrodite pid=17727) run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(RayWorkerAphrodite pid=17727) WARNING:  CUDA graphs can take additional 1~3 GiB of memory per GPU. If you are running out of memory, consider
(RayWorkerAphrodite pid=17727) decreasing `gpu_memory_utilization` or enforcing eager mode.
(RayWorkerAphrodite pid=17727) Capturing graph... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 35/35 0:00:00
(RayWorkerAphrodite pid=17727) INFO:     Graph capturing finished in 15 secs.
Capturing graph... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 35/35 0:00:00
INFO:     Graph capturing finished in 15 secs.
INFO:     Using the default chat template
INFO:     Started server process [16209]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:2242 (Press CTRL+C to quit)
INFO:     Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0
reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
```

but i still have the issue with TP 4
```
(aph) omni@DESKTOP-CKDOHD3:~$ python -m aphrodite.endpoints.openai.api_server --model TinyLLama/ -tp 4 --disable-custom-
all-reduce
2024-03-16 18:39:02,245 INFO worker.py:1724 -- Started a local Ray instance.
INFO:     Initializing the Aphrodite Engine (v0.5.1) with the following config:
INFO:     Model = 'TinyLLama/'
INFO:     DataType = torch.bfloat16
INFO:     Model Load Format = auto
INFO:     Number of GPUs = 4
INFO:     Disable Custom All-Reduce = True
INFO:     Quantization Format = None
INFO:     Context Length = 2048
INFO:     Enforce Eager Mode = False
INFO:     KV Cache Data Type = auto
INFO:     KV Cache Params Path = None
INFO:     Device = cuda
WARNING:  Possibly too large swap space. 16.00 GiB out of the 31.30 GiB total CPU memory is allocated for the swap
space.
Traceback (most recent call last):
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/endpoints/openai/api_server.py", line 563, in <module>
    engine = AsyncAphrodite.from_engine_args(engine_args)
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/engine/async_aphrodite.py", line 676, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/engine/async_aphrodite.py", line 341, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/engine/async_aphrodite.py", line 410, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/engine/aphrodite_engine.py", line 113, in __init__
    self._init_workers_ray(placement_group)
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/engine/aphrodite_engine.py", line 282, in _init_workers_ray
    self._run_workers("init_model", cupy_port=get_open_port())
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/engine/aphrodite_engine.py", line 1028, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/task_handler/worker.py", line 104, in init_model
    init_distributed_environment(self.parallel_config, self.rank,
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/task_handler/worker.py", line 287, in init_distributed_environment
    cupy_utils.init_process_group(
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/aphrodite/modeling/megatron/cupy_utils.py", line 87, in init_process_group
    _NCCL_BACKEND = NCCLBackendWithBFloat16(world_size, rank, host, port)
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/cupyx/distributed/_nccl_comm.py", line 70, in __init__
    self._init_with_tcp_store(n_devices, rank, host, port)
  File "/home/omni/miniconda3/envs/aph/lib/python3.10/site-packages/cupyx/distributed/_nccl_comm.py", line 100, in _init_with_tcp_store
    self._comm = nccl.NcclCommunicator(n_devices, nccl_id, rank)
  File "cupy_backends/cuda/libs/nccl.pyx", line 283, in cupy_backends.cuda.libs.nccl.NcclCommunicator.__init__
  File "cupy_backends/cuda/libs/nccl.pyx", line 129, in cupy_backends.cuda.libs.nccl.check_status
cupy_backends.cuda.libs.nccl.NcclError: NCCL_ERROR_UNHANDLED_CUDA_ERROR: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
```

**Comment by yamosin** [comment]
great, this issue fixed too
used `export NCCL_DEBUG=INFO` get problem detail is `NCCL WARN Cuda failure 'initialization error'`
found a fix on github by
`export NCCL_NVLS_ENABLE=0`
`export NCCL_IB_DISABLE=0`
some how it can work
